language: c  # Travis-CI does not currently support Python and Mac OS X

os:
  - linux
  - osx

env:
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - env: PYTHON_VERSION=3.7

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&
      curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
    else
      sudo apt-get update;
      sh -e /etc/init.d/xvfb start;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$PYTHON_VERSION
  - source activate test-environment
  - pip install .
  - pip install coveralls

script:
  - coverage run --source hyo2 setup.py test

after_success:
  - coveralls
