language: cpp  # Travis-CI does not currently support Python and Mac OS X

os:
  - linux
  - osx

env:
  - PYTHON_VERSION=3.8
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7

matrix:
  fast_finish: true
  allow_failures:
  - os: osx
  - env: PYTHON_VERSION=3.7

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set notify_outdated_conda false
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$PYTHON_VERSION
  - conda activate test-environment
  - python --version

  - conda install appdirs bidict cartopy gdal matplotlib-base numpy psutil pyproj
  - pip install coveralls PyYAML PySide2 pytest pytest-cov wheel
  - pip install -e .
  - conda list --show-channel-urls

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
       export QT_QPA_PLATFORM=offscreen;
    fi
  - py.test --cov
  - coverage report -m
  - coveralls

after_success:
  - python setup.py bdist_wheel
